### ISSUE TITLE
Conflict with Foundry Update V12 - Automatic Advancement with Subclass Not Working

### ISSUE THREAD

**Issue by Freezor** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#25]
After updating to the latest Foundry version, an issue with the module causes automatic advancement for characters with subclasses to fail. This results in a TypeError, preventing basic skill checks and saving throws unless characters are recreated with fresh sheets.

#### Error Message
The following error is encountered during automatic advancement:

```javascript
module.js:233 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at module.js:233:53
    at Array.map (<anonymous>)
    at Actor5e.prePreUpdateActor (module.js:223:8)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Actor.documentClass.prototype.update#0 (libWrapper-wrapper.js:189:20)
    at AdvancementManager._complete (advancement-manager.mjs:683:18)
    at AdvancementManager._forward (advancement-manager.mjs:575:15)
```

#### Steps to Reproduce
1. Update Foundry to the latest version.
2. Enable the "Link Item and Resource DnD5e" module.
3. Recreate characters using fresh sheets.
4. Attempt to automatically process character advancement with a subclass.

The process fails with a TypeError, indicating an attempt to read the 'value' property of an undefined object.

#### Environment
- **Foundry Version:** V12 Stable 330
- **D&D Module Version:** 3.3.1
- **Link Item and Resource DnD5e Module Version:** 2.1.2

**Comment by Zanfii** [comment]
Temporary fix until this gets updated you can do

Line 233 (the itemUpdates bit shown above)
```javascript
value: relevantItem.system.uses.value ?? 0, //relevantItem.system.uses.max if you want max, not current, value
```

Line 286 (in `handlePreAdvancementComplete` -> `updatesToOverriddenResource` loop)
```javascript
foundry.utils.setProperty(updateData, `system.resources.${resourceKey}`, {value: 0, max: 0, sr: false, lr: false, label: undefined});
```

Haven't thoroughly tested it but it the errors I was having with it and everything seems to work correctly

**Comment by Opius134** [comment]
Chiming in to keep the thread alive. Confirmed this is happening in my setup, and @Zanfii 's fix appears to work. Not sure if the fix causes any detrimental effect, so far everything seems alright.

**Comment by MrPrimate** [comment]
Can someone give me the names of class and subclass to level to replicate this please

**Comment by PwQt** [comment]
@MrPrimate for me it broke for Sorcerer - Wild Magic, having a resource of Tides of Magic

**Comment by Zanfii** [comment]
Yeah, it was the same for me, only seemed to cause issues when leveling Lunar Sorcery Sorcerer. Seemed to also break on the sorcery points here. 

Fighter, Ranger, and Cleric all worked fine I believe

**Comment by MrPrimate** [comment]
I have issued a new release which  resolved the issue for me based on @Zanfii work.
